# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Christopher Lewis
"""Install and remove the status line in the user's Claude Code settings.

Plugins cannot set ``statusLine`` themselves (a plugin's settings only honour
``agent`` and ``subagentStatusLine``), so ``setup`` edits the user's
``settings.json`` directly. It is careful about it: it refuses to touch a file it
cannot parse, writes a timestamped backup first, saves any existing status line
so et-ay can wrap it and later restore it, and is safe to run more than once.
"""

from __future__ import annotations

import json
import os
import shlex
import shutil
import stat
import time
from collections import OrderedDict
from pathlib import Path
from typing import Any, Dict, List, Optional

from . import paths
from .storage import atomic_write_json, atomic_write_text, read_json

SHIM_MARKER = "et-ay status line shim"

SHIM = """#!/bin/sh
# SPDX-License-Identifier: MIT
# {marker}. Generated by `et-ay setup`; safe to delete after `et-ay remove`.
#
# Claude Code runs this as your status line. It finds the currently installed
# et-ay plugin through the pointer file beside it, so plugin updates never break
# the status line. If et-ay or Python is unavailable it falls back to the status
# line you had before, so you are never left with nothing.
ANCHOR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
ROOT=$(cat "$ANCHOR/plugin_root" 2>/dev/null)
INPUT=$(cat)
OUTPUT=""
if [ -n "$ROOT" ] && [ -f "$ROOT/scripts/run.sh" ]; then
    OUTPUT=$(printf '%s' "$INPUT" | sh "$ROOT/scripts/run.sh" statusline)
fi
if [ -n "$OUTPUT" ]; then
    printf '%s\n' "$OUTPUT"
elif [ -f "$ANCHOR/wrapped_command" ]; then
    printf '%s' "$INPUT" | sh -c "$(cat "$ANCHOR/wrapped_command")"
fi
exit 0
"""


class SetupError(Exception):
    pass


def _load_settings(path: Path) -> OrderedDict[str, Any]:
    if not path.exists():
        return OrderedDict()
    raw = path.read_text(encoding="utf-8")
    if not raw.strip():
        return OrderedDict()
    try:
        data = json.loads(raw, object_pairs_hook=OrderedDict)
    except ValueError as error:
        raise SetupError(
            f"{path} is not plain JSON ({error}). et-ay will not edit a file it cannot "
            "parse safely. Add the statusLine entry by hand; see the README."
        ) from error
    if not isinstance(data, dict):
        raise SetupError(f"{path} does not contain a JSON object.")
    return data


def _backup(path: Path) -> Optional[Path]:
    if not path.exists():
        return None
    stamp = time.strftime("%Y%m%d-%H%M%S", time.localtime(paths.now()))
    target = path.with_name(f"{path.name}.et-ay-backup-{stamp}")
    shutil.copy2(path, target)
    return target


def _shim_command() -> str:
    return shlex.quote(str(paths.shim_path()))


def is_ours(line: Any) -> bool:
    if not isinstance(line, dict):
        return False
    command = str(line.get("command") or "")
    return str(paths.shim_path()) in command or "et-ay/statusline.sh" in command


def write_shim() -> Path:
    shim = paths.shim_path()
    atomic_write_text(shim, SHIM.format(marker=SHIM_MARKER))
    mode = shim.stat().st_mode
    shim.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return shim


def setup(
    root: Path,
    data: Path,
    refresh: int = 1,
    position: Optional[str] = None,
    wrap: bool = True,
) -> List[str]:
    """Install the status line. Returns human-readable notes on what changed."""
    notes: List[str] = []
    settings_file = paths.settings_path()
    settings = _load_settings(settings_file)

    paths.write_pointers(root, data)
    write_shim()
    notes.append(f"Status line shim written to {paths.shim_path()}")

    current = settings.get("statusLine")
    saved = read_json(paths.wrapped_path(), default=None)
    if current is not None and not is_ours(current):
        # A status line that is not ours: remember it so it can be wrapped now
        # and restored by `remove` later.
        saved = {"statusLine": current, "saved_at": paths.now()}
    elif not isinstance(saved, dict):
        saved = {"statusLine": None, "saved_at": paths.now()}
    saved["wrap"] = bool(wrap)
    atomic_write_json(paths.wrapped_path(), saved, indent=2)

    original = saved.get("statusLine")
    original_command = original.get("command") if isinstance(original, dict) else None
    wrapped_text = paths.anchor_dir() / "wrapped_command"
    if wrap and isinstance(original_command, str) and original_command.strip():
        atomic_write_text(wrapped_text, original_command + "\n")
        notes.append("Your existing status line is kept, with et-ay's estimate added to it.")
    else:
        try:
            wrapped_text.unlink()
        except OSError:
            pass
        if original_command:
            notes.append("Your existing status line was saved and comes back if you run remove.")

    # Keep a faster refresh the user already had, but not one et-ay set itself,
    # otherwise `setup --refresh 2` could never slow an existing install down.
    previous_refresh = current.get("refreshInterval") if isinstance(current, dict) and not is_ours(current) else None
    interval = int(refresh)
    if isinstance(previous_refresh, int) and 0 < previous_refresh < interval:
        interval = previous_refresh
    new_line: OrderedDict[str, Any] = OrderedDict()
    new_line["type"] = "command"
    new_line["command"] = _shim_command()
    if isinstance(current, dict) and isinstance(current.get("padding"), int):
        new_line["padding"] = current["padding"]
    new_line["refreshInterval"] = max(1, interval)

    if current == new_line:
        notes.append("settings.json already points at et-ay; nothing to change there.")
    else:
        backup = _backup(settings_file)
        if backup:
            notes.append(f"Backup of your settings saved as {backup.name}")
        settings["statusLine"] = new_line
        settings_file.parent.mkdir(parents=True, exist_ok=True)
        atomic_write_json(settings_file, settings, indent=2)
        notes.append(f"statusLine updated in {settings_file} (refreshing every {new_line['refreshInterval']}s)")

    if position:
        from . import config

        config.set_value("position", json.dumps(position))
        notes.append(f"Position set to {position}")
    return notes


def remove(purge: bool = False) -> List[str]:
    """Restore the status line that was there before et-ay, if any."""
    notes: List[str] = []
    settings_file = paths.settings_path()
    settings = _load_settings(settings_file)
    current = settings.get("statusLine")
    saved = read_json(paths.wrapped_path(), default=None)
    original = saved.get("statusLine") if isinstance(saved, dict) else None

    if is_ours(current):
        backup = _backup(settings_file)
        if backup:
            notes.append(f"Backup of your settings saved as {backup.name}")
        if original:
            settings["statusLine"] = original
            notes.append("Your previous status line is restored.")
        else:
            settings.pop("statusLine", None)
            notes.append("statusLine removed from settings.json (you had none before et-ay).")
        atomic_write_json(settings_file, settings, indent=2)
    elif current is None:
        notes.append("settings.json has no status line; nothing to restore.")
    else:
        notes.append("Your status line no longer points at et-ay, so it was left as it is.")

    if purge:
        anchor = paths.anchor_dir()
        if anchor.exists():
            shutil.rmtree(anchor, ignore_errors=True)
            notes.append(f"Removed {anchor}")
    else:
        notes.append(
            "Config and the shim are kept in "
            f"{paths.anchor_dir()} (use --purge to delete them). History is deleted "
            "by Claude Code when you uninstall the plugin."
        )
    return notes


def status() -> Dict[str, Any]:
    """What the settings file currently says, for the doctor command."""
    settings_file = paths.settings_path()
    try:
        settings = _load_settings(settings_file)
        error = None
    except SetupError as exc:
        settings, error = OrderedDict(), str(exc)
    line = settings.get("statusLine")
    shim = paths.shim_path()
    return {
        "settings_file": str(settings_file),
        "parse_error": error,
        "status_line": line,
        "installed": is_ours(line),
        "shim_exists": shim.exists(),
        "shim_executable": shim.exists() and os.access(shim, os.X_OK),
        "disable_all_hooks": bool(settings.get("disableAllHooks")),
        "wrapped": read_json(paths.wrapped_path(), default=None),
    }
